#!/bin/bash

if [ ! $# -eq 1 ]; then
	echo "usage grepShellcode <program-name>"
elif file $1 | grep -qi "ELF 32-bit LSB executable"; then
	objdump -d ./$1|grep '[0-9a-f]:'|grep -v 'file'|cut -f2 -d:|cut -f1-7 -d' '|tr -s ' '|tr '\t' ' '|sed 's/ $//g'|sed 's/ /\\x/g'|paste -d '' -s |sed 's/^/"/'|sed 's/$/"/g'

else
	echo "not an elf32 file"
fi

